-- AlterTable
ALTER TABLE `gangpackage` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `rule` ADD COLUMN `category` VARCHAR(191) NOT NULL DEFAULT 'RP';

-- AlterTable
ALTER TABLE `staff` ADD COLUMN `avatar` VARCHAR(191) NULL;
