### Register User

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "soroush",
    "email": "soroush@icerp.com",
    "password": "123456"
}

### Login User

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "soroush@icerp.com",
    "password": "123456"
}

### Admin Panel

GET http://localhost:5000/api/admin/panel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImZvdW5kZXIiLCJpYXQiOjE3ODQ1ODkzMDcsImV4cCI6MTc4NTE5NDEwN30.kYp7uBbx4L57RLO-vgbRczAi-zyReKbgTs3dtCnE13c